<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="Unity.Multiplayer.Center.Editor" elementFormDefault="qualified" targetNamespace="Unity.Multiplayer.Center.Editor" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="UnityEngine.UIElements.xsd" namespace="UnityEngine.UIElements" />
  <xs:complexType name="PackageItemType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q1="UnityEngine.UIElements" base="q1:VisualElementType">
        <xs:choice />
        <xs:attribute name="package-id" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PackageItem" xmlns:q2="UnityEngine.UIElements" substitutionGroup="q2:VisualElement" type="tns:PackageItemType" />
  <xs:complexType name="PackageIconType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q3="UnityEngine.UIElements" base="q3:VisualElementType">
        <xs:choice />
        <xs:attribute name="package-id" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PackageIcon" xmlns:q4="UnityEngine.UIElements" substitutionGroup="q4:VisualElement" type="tns:PackageIconType" />
  <xs:complexType name="DelayedPackageDocumentationBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q5="UnityEngine.UIElements" ref="q5:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q6="UnityEngine.UIElements" type="q6:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q7="UnityEngine.UIElements" type="q7:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q8="UnityEngine.UIElements" type="q8:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q9="UnityEngine.UIElements" type="q9:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageDocumentationBinding" type="tns:DelayedPackageDocumentationBindingType" />
  <xs:complexType name="PackageInfoBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q10="UnityEngine.UIElements" ref="q10:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q11="UnityEngine.UIElements" type="q11:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q12="UnityEngine.UIElements" type="q12:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q13="UnityEngine.UIElements" type="q13:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q14="UnityEngine.UIElements" type="q14:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="PackageInfoBinding" type="tns:PackageInfoBindingType" />
  <xs:complexType name="HyperLinkType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q15="UnityEngine.UIElements" base="q15:LabelType">
        <xs:choice />
        <xs:attribute name="u-r-l" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="HyperLink" xmlns:q16="UnityEngine.UIElements" substitutionGroup="q16:Label" type="tns:HyperLinkType" />
  <xs:complexType name="ColoredMinMaxSliderType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q17="UnityEngine.UIElements" base="q17:MinMaxSliderType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ColoredMinMaxSlider" xmlns:q18="UnityEngine.UIElements" substitutionGroup="q18:MinMaxSlider" type="tns:ColoredMinMaxSliderType" />
  <xs:complexType name="ImageWithPlaceholderElementType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q19="UnityEngine.UIElements" base="q19:ImageType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ImageWithPlaceholderElement" xmlns:q20="UnityEngine.UIElements" substitutionGroup="q20:Image" type="tns:ImageWithPlaceholderElementType" />
  <xs:complexType name="DelayedPackageInstalledBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q21="UnityEngine.UIElements" ref="q21:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q22="UnityEngine.UIElements" type="q22:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q23="UnityEngine.UIElements" type="q23:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q24="UnityEngine.UIElements" type="q24:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q25="UnityEngine.UIElements" type="q25:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageInstalledBinding" type="tns:DelayedPackageInstalledBindingType" />
  <xs:complexType name="RecommendationsGridType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q26="UnityEngine.UIElements" base="q26:VisualElementType">
        <xs:choice />
        <xs:attribute name="item-template" type="xs:string" />
        <xs:attribute name="recommendations" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="RecommendationsGrid" xmlns:q27="UnityEngine.UIElements" substitutionGroup="q27:VisualElement" type="tns:RecommendationsGridType" />
  <xs:complexType name="DelayedPackageIdBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q28="UnityEngine.UIElements" ref="q28:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q29="UnityEngine.UIElements" type="q29:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q30="UnityEngine.UIElements" type="q30:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q31="UnityEngine.UIElements" type="q31:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q32="UnityEngine.UIElements" type="q32:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageIdBinding" type="tns:DelayedPackageIdBindingType" />
  <xs:complexType name="DelayedPackageNameBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q33="UnityEngine.UIElements" ref="q33:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q34="UnityEngine.UIElements" type="q34:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q35="UnityEngine.UIElements" type="q35:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q36="UnityEngine.UIElements" type="q36:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q37="UnityEngine.UIElements" type="q37:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageNameBinding" type="tns:DelayedPackageNameBindingType" />
  <xs:complexType name="CategoriesContainerType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q38="UnityEngine.UIElements" base="q38:ScrollViewType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="CategoriesContainer" xmlns:q39="UnityEngine.UIElements" substitutionGroup="q39:ScrollView" type="tns:CategoriesContainerType" />
  <xs:complexType name="HelpIconType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q40="UnityEngine.UIElements" base="q40:VisualElementType">
        <xs:choice />
        <xs:attribute name="documentation-url" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="HelpIcon" xmlns:q41="UnityEngine.UIElements" substitutionGroup="q41:VisualElement" type="tns:HelpIconType" />
  <xs:complexType name="QuestionModeSwitcherType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q42="UnityEngine.UIElements" base="q42:VisualElementType">
        <xs:choice />
        <xs:attribute default="false" name="question-mode" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="QuestionModeSwitcher" xmlns:q43="UnityEngine.UIElements" substitutionGroup="q43:VisualElement" type="tns:QuestionModeSwitcherType" />
  <xs:complexType name="DelayedPackageDescriptionBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q44="UnityEngine.UIElements" ref="q44:VisualElement" />
      <xs:element minOccurs="0" form="unqualified" name="Style" xmlns:q45="UnityEngine.UIElements" type="q45:StyleType" />
      <xs:element minOccurs="0" form="unqualified" name="Template" xmlns:q46="UnityEngine.UIElements" type="q46:TemplateType" />
      <xs:element minOccurs="0" form="unqualified" name="AttributeOverrides" xmlns:q47="UnityEngine.UIElements" type="q47:AttributeOverridesType" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q48="UnityEngine.UIElements" type="q48:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageDescriptionBinding" type="tns:DelayedPackageDescriptionBindingType" />
</xs:schema>